trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

parameters:
- name: someString
  type: string
  default: "HELLO"    

variables:
   A: ${{ lower(parameters.someString) }}

steps:
  - script: echo $A # outputs hello