name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:

- task:  ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: 'latest'
    terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'
- task: TerraformCLI@1
  displayName: 'check terraform version'
  inputs:
    command: version
- task: TerraformCLI@1
  displayName: "Terraform Init"
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'ARMConnection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'tfclirg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'tfclisa'
    backendAzureRmContainerName: 'tfclicont'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@1
  displayName: "Terraform Plan"
  inputs:
    command: 'plan'
    environmentServiceName: 'ARMConnection'
    commandOptions: '-out=terraform.tfplan'
    allowTelemetryCollection: true
    publishPlanResults: 'terraform.tfplan'
- task: TerraformCLI@1
  displayName: "Terraform Apply"
  inputs:
    command: 'apply'
    allowTelemetryCollection: true
