trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

parameters:
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - Stg
  - Prd

variables:
  lowerEnvironment: ${{ lower(parameters.Environment) }}
  Prefix: ${{ lower('TFAZDO') }}
  DeploymentDefaultLocation: 'westeurope'
  ServiceConnectionName: 'ARMConnection'
  TerraformDirectory: "${{ lower(parameters.Environment) }}-dir"
  AzureSubscriptionServiceConnectionName: $(ServiceConnectionName)
  TerraformStateStorageAccountResourceGroupName: "$(Prefix)-${{ lower(parameters.Environment) }}-rg"
  TerraformStateStorageAccountName: "$(Prefix)-${{ lower(parameters.Environment) }}-sa"
  TerraformStateStorageAccountContainerName: "$(Prefix)-${{ lower(parameters.Environment) }}-cont"

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job:
    steps:
    - script: echo Hello world!
      displayName: 'echo Hello world!'
    - script: |
        echo lowerEnvironment $(lowerEnvironment)
        echo Buildnumber $(Build.BuildNumber)
        echo ServiceConnectionName $(ServiceConnectionName)
        echo DeploymentDefaultLocation $(DeploymentDefaultLocation)
        echo TerraformDirectory $(TerraformDirectory)
        echo AzureSubscriptionServiceConnectionName $(AzureSubscriptionServiceConnectionName)
        echo TerraformStateStorageAccountResourceGroupName $(TerraformStateStorageAccountResourceGroupName)
        echo TerraformStateStorageAccountName $(TerraformStateStorageAccountName)
        echo TerraformStateStorageAccountContainerName $(TerraformStateStorageAccountContainerName)
      displayName: 'echo Variables'
    - script: |
        echo Environment ${{ lower(parameters.Environment) }}
      displayName: 'echo Parameters'
- stage: Stage2
  displayName: "Stage 2"
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@0
      displayName: Terraform Install
      inputs:
        terraformVersion: 1.5.6
    - task: TerraformCLI@0
      displayName: 'Terraform : init'
      inputs:
        command: init
        backendType: azurerm
        workingDirectory: $( TerraformDirectory )
        backendServiceArm: $( AzureSubscriptionServiceConnectionName )
        backendAzureRmResourceGroupName: $( TerraformStateStorageAccountResourceGroupName )
        backendAzureRmStorageAccountName: $( TerraformStateStorageAccountName )
        backendAzureRmContainerName: $( TerraformStateStorageAccountContainerName )
        backendAzureRmKey: ${{ parameters.Environment }}.tfstate

