name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:

- task:  ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.5.6'
    terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ARMConnection'
    backendAzureRmResourceGroupName: 'terraformazdorg'
    backendAzureRmStorageAccountName: 'terraformazdosa'
    backendAzureRmContainerName: 'terraformazdocont'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'ARMConnection'