trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

parameters:
- name: someString
  type: string
  default: "HELLO"    

variables:
   A: ${{ lower(parameters.someString) }}

steps:
  - script: echo $(A) # outputs hello