trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

parameters:
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - Stg
  - Prd

variables:
- name: DeploymentDefaultLocation
  value: 'westeurope'
- name: ServiceConnectionName
  value: 'ARMConnection'

stages:
- stage: Stage1
  displayName: "Stage 1"
  jobs:
  - job:
    steps:
    - script: echo Hello world!
      displayName: 'echo Hello world!'
    - script: |
        echo Buildnumber $(Build.BuildNumber)
        echo ServiceConnectionName $(ServiceConnectionName)
        echo DeploymentDefaultLocation $(DeploymentDefaultLocation)
      displayName: 'echo Variables'
    - script: |
        echo Environment ${{ parameters.Environment }}
        echo environment ${{ parameters.environment }}
      displayName: 'echo Parameters'
- stage: Stage2
  displayName: "Stage 2"
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@0
      displayName: Terraform Install
      inputs:
        terraformVersion: 1.5.6