trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

parameters:
- name : Environment
  displayName: Environment to deploy.
  type: string
  default: Dev
  values:
  - Dev
  - Stg
  - Prd

variables:
   lowerEnvironment: ${{ lower(parameters.Environment) }}

steps:
  - script: echo $(lowerEnvironment) # outputs hello