trigger:
    batch: true
    branches:
      include:
      - main
  
pool:
  vmImage: 'windows-2022'

parameters:
- name : Environment
  displayName: Environment to deploy to.
  type: string
  default: Dev
  values:
  - Development
  - Staging
  - Production


variables:
- group: GlobalVariables
- name: DeploymentDefaultLocation
  value: 'westeurope'
- name: ServiceConnectionName
  value: 'ARMConnection'

steps:
- task: TerraformTaskV4@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@1
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)'
    backendType: 'azurerm'
    ensureBackend: true
    backendServiceArm: $(ServiceConnectionName)
    resourceGroupName: 'terraformazdorg'
    storageAccountName: 'terraformazdosa'
    containerName: 'terraformazdocont'
    key: 'tf/terraform.tfstate'

- task: TerraformTaskV4@3
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: TerraformTaskV4@3
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceName: $(ServiceConnectionName)
    commandOptions: '-out=tfplan'

- task: TerraformTaskV4@3
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceName: $(ServiceConnectionName)
    commandOptions: '-auto-approve -input=false tfplan'
