trigger:
    batch: true
    branches:
      include:
      - main
  
pool:
  vmImage: 'windows-2022'

parameters:
- name : Environment
  displayName: Environment to deploy to.
  type: string
  default: - Development
  values:
  - Development
  - Staging
  - Production

